### ISSUE TITLE
Concerns about Support statement in Lite documentation

### ISSUE THREAD

**Issue by bwentwor** [IBM-Bluemix-Docs/pricing#4]
I am referencing the following page:
https://console.bluemix.net/docs/pricing/index.html#liteaccount

In the "What's available?" section, it says "Free IBM Cloud support." Although they have access to IBM Cloud Support, as confirmed by Jim McVea, Support is limited to "best effort." I wonder if that expectation should be clearer. For example perhaps it should say "Free IBM Cloud support (best effort)" and stress the use of the forums.

**Comment by cdmauney** [comment]
Following up with Bill via Slack.

**Comment by cdmauney** [comment]
Updates delivered: https://console.bluemix.net/docs/pricing/index.html#liteaccount.
